<a href="https://colab.research.google.com/github/jerson-herrera/p..prueba/blob/main/jueves_en_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import itertools
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [61]:
DatasetName = "/content/zoo.data"
Data = pd.read_csv(DatasetName, sep=',', header=None)

#DatasetName = 'newThyroid.csv'
#Data = pd.read_csv(DatasetName, sep=',')

Data.head()


#Data.describe()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0  aardvark   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   
1  antelope   1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1   
2      bass   0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0   
3      bear   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   
4      boar   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   

   17  
0   1  
1   1  
2   4  
3   1  
4   1

In [ ]:
NumSamples = Data.shape[0]
dataClass1 = Data.loc[Data[:][17]==1]
dataClass2 = Data.loc[Data[:][17]==2]
dataClass3 = Data.loc[Data[:][17]==3]
dataClass4 = Data.loc[Data[:][17]==4]
dataClass5 = Data.loc[Data[:][17]==5]
dataClass6 = Data.loc[Data[:][17]==6]
dataClass7 = Data.loc[Data[:][17]==7]

NumSamplesClass1 = dataClass1.shape[0]
NumSamplesClass2 = dataClass2.shape[0]
NumSamplesClass3 = dataClass3.shape[0]
NumSamplesClass4 = dataClass4.shape[0]
NumSamplesClass5 = dataClass5.shape[0]
NumSamplesClass6 = dataClass6.shape[0]
NumSamplesClass7 = dataClass7.shape[0]

print('Número total de animales:',NumSamples)
print()
print('Número de animales de la Clase 1 (Mamíferos Terrestres): '"Son",NumSamplesClass1,"Animales."'Los cuales equivalen al(',100*NumSamplesClass1/NumSamples,' %)de todos los animales.')
print('Número de animales de la Clase 2 (Aves): '"Son",str(NumSamplesClass2),"Animales."'Los cuales equivalen al (',str(round(100*NumSamplesClass2/NumSamples))+' %)de todos los animales.')
print('Número de animales de la Clase 3 (Reptiles): '"Son",str(NumSamplesClass3),"Animales."'Los cuales equivales al (',str(round(100*NumSamplesClass3/NumSamples))+' %)de todos los animales.')
print('Número de animales de la Clase 4 (Peces):'"Son",str(NumSamplesClass4),"Animales."'Los cuales equivales al ('+str(round(100*NumSamplesClass4/NumSamples))+' %)de todos los animales.')
print('Número de animales de la Clase 5 (Anfibios):'"Son",str(NumSamplesClass5),"Animales."'Los cuales equivales al ('+str(round(100*NumSamplesClass5/NumSamples))+' %)de todos los animales.')
print('Número de animales de la Clase 6 (Insectos):'"Son",str(NumSamplesClass6),"Animales."'Los cuales equivales al ('+str(round(100*NumSamplesClass6/NumSamples))+' %)de todos los animales.')
print('Número de animales de la Clase 7 (Moluscos y otros):'"Son",str(NumSamplesClass7),"Animales."'Los cuales equivales al ('+str(round(100*NumSamplesClass7/NumSamples))+' %)de todos los animales.')


In [ ]:
DataAsNumpy = np.concatenate((dataClass1.values, dataClass2.values, dataClass3.values,dataClass4.values, dataClass5.values,dataClass6.values, dataClass7.values ), axis=0)
#X = DataAsNumpy[:,(0,3)]
X = DataAsNumpy[:,1:16] #En este caso, selecciona desde la columna con índice 1 (segunda columna, ya que los índices comienzan en 0) hasta la columna con índice 15 (la decimosexta columna).
Y = DataAsNumpy[:,17]
print(X.shape)
print(Y.shape)


print(X)
print(Y)


In [ ]:
#porcentaje de las esquinas
a=X[0][0]
b=X[0][14]
c=X[100][0]
d=X [100][14]
print(a)
print(b)
print(c)
print(d)
porcentaje= a+b+c+d
div=porcentaje/4
print("El porcentaje de las cuatro esquinas es de: ",div)

In [ ]:
#El promedio de toda la segunda fila
promedio_fila_2 = np.mean(X[1,:]) #np.mean() sirve para calcular el promedio de los valores en filas o columnas.
print("El promedio de la fila 2 es:", promedio_fila_2)



In [ ]:
#El numero mayor de la fila numero 11
maximo_fila_3 = np.max(X[11,:])#np.max() sirve para calcular el numero maximo de los valores en filas o columnas: en este caso,fila 11, todas las columnas
print("El numero mayor de la fila 3 es:", maximo_fila_3)

In [ ]:
#El numero minimo de la fila numero 1
minimo_fila_1 = np.min(X[1,:])#np.max() sirve para calcular el numero maximo de los valores en filas o columnas: en este caso,fila 11, todas las columnas
print("El numero mayor de la fila 3 es:", minimo_fila_1)

In [ ]:
#////////Reemplazar la ultima fila por puros"9"//////////

# Supongamos que tienes una matriz NumPy llamada "X" y copias los valores originales de la segunda fila
#valores_originales = X[1, :].copy()
# Asignar el valor 9 a todas las columnas de la segunda fila
#dato = 9
#X[1, :] = dato
# Ahora, si deseas restaurar los valores originales:
#X[1, :] = valores_originales


dato=9
X[1][:]=dato
print(X)

In [ ]:
#Agregar una nueva fila que contenga puros 8
nueva_fila = np.full(X.shape[1],8) #np.full(), que llena la fila con el valor 8


X=np.vstack((X,nueva_fila)) #np.vstack() para agregar esta nueva fila al final de la matriz existente
print(X)

In [62]:
#Borrar dos columnas la 2 y la 3
#axis=1, indica que estamos eliminando columnas (el valor predeterminado es axis=0 para eliminar filas).
print(X)

columnas_eliminar=[13,14]
new=np.delete(X,columnas_eliminar, axis=1)

print("Matriz despues de elimanr las columnas 2 y 3")
print(X)





[[1 0 0 ... 4 0 0]
 [9 9 9 ... 9 9 9]
 [1 0 0 ... 4 0 0]
 ...
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [7 7 7 ... 7 7 7]]
Matriz despues de elimanr las columnas 2 y 3
[[1 0 0 ... 4 0 0]
 [9 9 9 ... 9 9 9]
 [1 0 0 ... 4 0 0]
 ...
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [7 7 7 ... 7 7 7]]
